# Site settings
title: SP Ventures
email: your-email@domain.com
description: > # A SP Ventures é referência na condução de investimentos em Venture Capital no Brasil.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
